### ISSUE TITLE
How to trigger an action when clicking on a row?

### ISSUE THREAD

**Issue by kaned** [gerard2p/ember-cli-crudtable#1]
How can I have an action triggered when I click on a row? The simplest example would be that I want to click on a row and have it redirect me to a page to view the full details for the item I selected.

Is there a way to do this?

**Comment by gerard2p** [comment]
Hello kaned,
of course there's a simple way of doing I've actually implemented that in a project, give me a couple of hours and I'll with upload the first beta version of May, and I'll also let you know how to.

**Comment by gerard2p** [comment]
I've Updated the read me, you can see a little example of how to manage that feature.

**Comment by kaned** [comment]
This works great! Nice and easy to setup, just like the rest of CRUD Table.

Question... if I needed to have multiple crud tables, each linking to different pages, how can I specify the link to use? Right now the link is hardcoded in the template.hbs file. Is there a parameter in the fieldDefinition that I could use to pass a link/value to the template?

**Comment by gerard2p** [comment]
Unfortunately not right now, I've not defined a link-datatype or a custom field to pass information un the templates, but I'm working on one-to-one relationships... maybe thats what you're looking for ...

**Comment by kaned** [comment]
Alright, I'll keep an eye out for that and try it. I'll close this in the meantime since the question was answered and you provided a nice simple solution. Thanks!
