### ISSUE TITLE
Change the default GET request string

### ISSUE THREAD

**Issue by theonastos** [gerard2p/ember-cli-crudtable#10]
New to ember here,

I would like to know if there is a way to change the default get URL from this /posts?page=1 to this /posts?page[1].
I'm having an issue because of my backend(Rails API)

**Comment by gerard2p** [comment]
No, right now ... can you give a link so I can check the Rails API url queries to extend the functionality and add the support for this kind or url request.

Thanks.

**Comment by theonastos** [comment]
[Example Link of my backend API](https://quiet-hamlet-74790.herokuapp.com/posts?page[number]=1&page[size]=3)
As I understand Ember is not able yet to use hash-like structures for the query parameters.

Here is an example of how rails query parameters are defined in my app

```
def index
    if params[:page]
      @posts = Post.page(params[:page][:number]).per(params[:page][:size])
    else
      @posts = Post.page.all
    end

    render json: @posts
end
```

Have a look at this line of code:
`@posts = Post.page(params[:page][:number]).per(params[:page][:size])`

**Comment by gerard2p** [comment]
I'm checking this RFC http://tools.ietf.org/html/rfc3986#section-3.4
Becouse I don't really know if it is a standard or not, but soon I'll give you an awser.

**Comment by gerard2p** [comment]
Hello again, I just ran a test and what you want to do is totally supported.
In the last update I added a new paginator object, which allows you to personalize the object that will be converted into the query body.

Long story shot.
create a file called _app/paginator/_**crudtable.js**

```javascript
import Ember from 'ember';
import pagination from 'ember-cli-crudtable/mixins/pagination';
export default Ember.Object.extend(pagination,{
	getBody(page, query) {
		query.page = undefined === query.page ? query.page || {number:0,size:10};
		query.page.number=page;
		query.page.size=this.get('limit');
	}
});
```

The serializer for ember-data does the rest, but if you have a custom serializer, you may have to write some code to manage it.

Let me know if this works for you.

[Paginator Mixin](https://github.com/gerard2p/ember-cli-crudtable/blob/3ef30db728a101b4827c1b8cc3ea231fa66ac0f0/addon/mixins/pagination.js)
