### ISSUE TITLE
Using Mirage with ember-cli-crudtable

### ISSUE THREAD

**Issue by choclaudio** [gerard2p/ember-cli-crudtable#12]
I am trying to do the example from the webpage, but the table is not loading any data, the request is being made and mirage is responding.

School Model:

```
import DS from 'ember-data';
let attr = DS.attr;
export default DS.Model.extend({
    Name: attr('string'),
    City: attr('string'),
    Location:attr('string'),
    Zoom:attr('number'),
    Address: attr('string'),
    CP: attr('string'),
    Responsible:attr('string'),
    AmountStudents:attr('number')
});
```

School Controller:
```
import Ember from 'ember';
import CTABLE from 'ember-cli-crudtable/mixins/crud-controller';

let CrudTable = CTABLE('school');
export default Ember.Controller.extend(CrudTable,{
    fieldDefinition:{
        Name:{Label:'School'},
        Responsible:{
            Label:'Manager',
            Type:'text',
            Search: true
        },
        Location:{
            Label:'Google Map',
            Type:'googlemap',
            Display:'City',
            Zoom:'Zoom'
        },
    }
});
```

Mirage config:
```
export default function() {  
  this.get('/schools', () => {
    return {
      school: [
        {id: 1, Name: 'Zelda', City: "Some City", Location: 'Link', Zoom: 'Gannon', Address: 'Metroid', CP: 'Super Mario', Responsible: 'Zen', AmountStudents: 'Doom'}
      ]
    };
  });
}
```

How should the API response look?
Will Mirage work with ember-cli-crudtable?

**Comment by JensNordenbro** [comment]
:) ...had the same problem....

**Comment by gerard2perez** [comment]
Hello, I'm a little bit busy today but definitely I'll be checking it, so tomorrow I can give you a solution.

**Comment by gerard2perez** [comment]
@choclaudio @JensNordenbro I'm sorry I take me so long to awnser, but actually the solution it quite easy.
Ember by default uses the **JSONAPIAdapter**/**JSONAPISerializer**, so mirage by default implements a **JSONAPISerializer**.

And the response you write for mirages will need tje **RESTSerializer**/**RESTAdapter**.

So this is what you need to do to use that kind of data:

1. Add to the file app/adapters/application.js
```
import RESTAdapter from 'ember-data/adapters/rest';

export default RESTAdapter.extend();
```

2. Make sure mirage/serializers/application.js looks like:
```
import { RestSerializer } from 'ember-cli-mirage';

export default RestSerializer.extend();

```

If my explanation still unclear you can try:
https://github.com/gerard2p/ember-cli-crudtable-mirage.git

**Comment by choclaudio** [comment]
Great job!! Thank you for the response!
