### ISSUE TITLE
Data is not shown

### ISSUE THREAD

**Issue by 0x0badc0de** [gerard2p/ember-cli-crudtable#4]
Minimal example from readme doesn't work.
Issue seems to be caused by the last commit which changes addon/components/crud-table.js
```
-                    List: cmp.fields[field].List === true,
+                    List: cmp.fields[field].List === false ? true:false,
```
Reverting to 1.0.1 and explicitly specifying 'List: true' in defs fixes the issue.

**Comment by gerard2p** [comment]
I'll eat something and then check it up, thanks!

**Comment by gerard2p** [comment]
As you pointed out the v1.0.2 made the property to be default at false, so I've fixed it and also check compatibility with the latest version of ember and ember-data.
